### ISSUE TITLE
eng: 8th Oct ichigo.homebrew.ltd Demo

### ISSUE THREAD

**Issue by dan-homebrew** [homebrewltd/ichigo#68]
## Goal

- 8th October demo at our event
- Intended as a server-side demo: learnings to be then applied in https://github.com/janhq/jan/issues/3488 (Sprint 22-23)

## Questions

- What data can we collect from a Research Demo, that can help us improve our model?
- Can we show latency, token speed, etc?

## Tasklist

- [ ] #70
- [ ] Architecture for ichijo.homebrew.ltd @louis-jan @nguyenhoangthuan99 (use this thread)
- [ ] epic: Infra for Ichigo and Fish Speech
- [ ] epic: Solve for Desktop vs. Mobile microphone or sound capture issue
- [ ] epic: Data Collection for thumbs-up, thumbs-down data
- [ ] epic: Continuous Voice Detection on client-side
- [ ] epic: User can choose voice
- [ ] epic: Stats for Latency, token speed etc

### Features

- Be very clear with users that this is a Research Demo, and data will be used
- ChatUI with transcription
- Voice detection on client-side? (fallback: Press-to-talk)
- TTS for replies (plus: voice selector): Fish Speech, etc
- Data will be used for Research Purposes
- Collect Thumbs up/Thumbs down for poor transcription or reply -> Saved and persisted to DB
- Each Session should be unique for a user (by cookie?)
- Function Calling? 

### Design

![Image](https://github.com/user-attachments/assets/1c463c1b-358e-4dd0-b153-783b7817aede)

![Image](https://github.com/user-attachments/assets/253bf176-47af-4a7d-b1aa-b53c2e98aa7c)

**Comment by dan-homebrew** [comment]
@louis-jan @urmauur @namchuai I would like to explore doing the Ichijo demo as a fork of Jan, that is run server-side: 

## Why?
- I would like to focus our efforts on improving Jan, vs. support an additional orphaned repo
- Opportunity: implement swappable persistence layer (e.g. persistence vs. filesystem)
- Opportunity: implement "multi-user" (i.e. you don't see others' convos when hosted server side)
- Opportunity: implement feedback loops (i.e. thumbs up/thumbs down), which helps us generate datasets

## Roadmap

- Ichijo Demo will be a fork of Jan that is run server-side (with hidden UI)
- In the future, this will be merged into Jan as "Voice Mode" (look at ChatGPT Mobile for an example)

## Scope

- Jan should have a "Voice Mode" UI, which we will use for the Ichijo demo
- TBD: Ichijo demo is Jan with a 2nd persistence extension (DB, vs. filesystem) 
- TBD: Ichijo demo is Jan with "multi-user" in DB (i.e. use session_id), to ensure Threads are associated with Session (we don't need a full user abstraction for now)
- TBD: Ichijo demo is Jan with some a "thumbs down" or "thumbs up" on `threads > messages`, to collect RL type dataset

## Out-of-scope

- Ichijo demo should not need to show past conversations (i.e. refresh page = new thread)
- Jan Voice Mode - this is out-of-scope to Sprint 22 or Sprint 23 as I think Jan has a lot of cross-platform edge cases and it is not feasible for us to rush this to market

Everything we do for this demo, should add towards Jan being able to support Voice Mode though - this should not be a separate repo.

**Comment by 0xSage** [comment]
This is what Ichigo reminds me of:

https://www.gatesnotes.com/Tomorrow-and-Tomorrow-and-Tomorrow

```
Although there are plenty of video games mentioned in the book—*Oregon
Trail* is a recurring theme—I’d describe it more as a story about
partnership and collaboration. When Sam and Sadie are in college, they
create a game called *Ichigo* that turns out to be a huge hit. Their
company, Unfair Games, becomes successful, but the two start to butt
heads...
```

The book was ok, I give it 3 out of 5 stars, but it has a big fan base.
Very cute name. I dont mind it.

**Comment by tikikun** [comment]
@louis-jan @urmauur @nguyenhoangthuan99 
reference codebase https://github.com/tikikun/public_demo_llama3s

**Comment by louis-jan** [comment]
# Ichigo as an additional orphaned repository

## Separation of Concerns
1. Will we remove any irrelevant parts that could cause side effects? E.g. CI Pipelines that push release artifacts to Jan's S3.
> To me, it should only add more features if it's intended for a short-lived repository. Otherwise, it would make syncing them up or merging them back a nightmare. 

2. It's a `server-side demo` - going back to the previous Jan web server demo. How does the current architecture work?
> Conversational extension is the only one involved for now. You can disable the others, as the demo works with remote endpoints.

3. Should it be an extension DB or filesystem? 
> To me, multi-user support works better with a relational DB. The filesystem would take more effort. E.g. An auto-generated endpoints DB system would be great. 
> Audio files will be stored in a single location (is that a bad idea?)

4. How does the content rating system work?
> It would be great to be part of the message object. It is a part of the Message Update endpoint, so no need to introduce a new one?

|Ichigo|
|:-:|
|![47284](https://github.com/user-attachments/assets/aa28fdb7-4206-49d7-a484-328298d5c95a)|


[Draw.io](https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=ichigo.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Page-1%22%20id%3D%220Fr_y4jCqiVOhq0ZBT_t%22%3E7Vtbc9o4FP41zKQPyfhu8xggZLvTzmaWdNo%2B7Qhbxm6MRSU5gf76lXy3JQgJNk5m8pJYB0nI3%2FmOzkVipE%2FX21sMNsFX5MFopCnedqTPRpqmWZbN%2FnHJLpOoGm9yyQqHXi6rBIvwD8yFSi5NQg%2BSRkeKUETDTVPoojiGLm3IAMboqdnNR1HzWzdgBQXBwgWRKP0eejTIpI6pVPK%2FYLgKim9WlfyTNSg65wISAA891UT6zUifYoRo9rTeTmHE0StwycbN93xaLgzDmB4zAEF3qyzc5PbHd%2FsWmPc338jtpZEv7hFESf7Gn90gXCEm%2Bxz7GORrp7sCEIyS2IN8TmWkT56CkMLFBrj80yfGASYL6DpiLZU9eoAEaV%2FeeISYhgzZ6yhcxUxGEe%2Fth1E0RRHC6fT6fD43bnQmJxSjB1j7xLOWlmmxT%2FIVs9ngdi8Waokw4yZEa0jxjnXJB5gFvXJa6nnzqVJx2SWoqXdcaBfktFqVU1fIs4cc%2FBcoYizoYcLJCzETXkwReggh%2BXSaMgKEwz8opiA6qJAO4L3U7CvzOYCNcdnpPBBrh6hOIfY5cAztv0Gc7hT44UTAQY6rC%2Fn0x1qAB6DjuzILsFwHLv1uVKQ19WNJ9KNIDMAx%2BtKOuV87UxSzdyWAhigGfKKbLYUxYa3T9NMb%2F402%2FQ1HxFc3JezXx33hawj4fk2YG71Msj3GbWHc867fBchNiFX1WIh7o7CqCbhBj0UTeRNhGqAVh%2Femkk6ayFZ9viAOVArhL0jpLg%2BNQEJRE224DekPPvyK2XTW%2FFn7aLbNp04bu7yRLZSv7jD67GVQgl34PLEowCtID6GjyNWJYcRY99hciEw36dBrjMGu1mGDwpiS2sx3XFCxRNWNBk1MqxUlvaw%2Fe8hWULGkfJXXE8cahDcxW3RGHPbOeftn2lbMol2xJ23t6q07iEP25tyzdc0p%2FVhO6Sdy6rQtVYwovkJCeEahKXdgFyHgSTX7BSxZnvSyWGEdel6meEjCP2CZzsdhzy2ATW5ORubs0OaaJ0n54FGZmtRVtJ%2Bg%2B8M9xiDVsBt2U6jwZdZdmWPRBfk%2BYRRoq6oDo9PFgCPeJPy7F0E6fK8LVJ93gR34N1VtOjhZDF1qsO7g1N4iaFXMFmfsVZVrD2w4a99mNGY3cz1rLMHRlOHYX6Ag454P2QulGUgJpwXWHIN4SSoo3hy8JUyFx9SGx1cMdhmYEeWxafjYANH6nfACzKTxtMr%2FpyPIJs0HxSFL4D6sUh1culmSds0XFoc05Cn2gSl9lO5xPnCbM96DAK2BdFyDCRSDmLAEdZ07mYtPIleUV4rscpUM%2BmyhzcUzcQaJIE6xbUrfK9zpuCWWvOQHJB%2BQ7IekZUsz0eK6QK3lB9jeTeXRZAR9eiiWlPmMplfpwkGYLQdhiw5C1SUOwuytEjhwwjVqZFvPJVucKPUqoH09Gc9HYt3QhI7HEzmhbuhoS92qKuedZGiqfWSKlhUaz532606Lc45TZ82z%2FVXFbLGsh7S%2FwLAWpnjQRR68TrwQXRyqPp8pBbFbxRDbFCx3LDHcorjcveE6gxhuXmErnmtmu7fA9mpjbxq177jQlR4GLB3TMDsuu6jOsUZtn2jUp4X3jmA3YZE%2BvUGrsZSBrUYVDxffe%2BR1OB0ikPDTof9C76jE6CPl%2BYjvPyD5SHm6S3la0aRtDJ3x6IMeTb4ucLqyy2CpPNA8EDl1GAdp2rFx0HjIOKhYZs2vT%2F%2F9xv4p5THU0KGQ0jIEyT2Is4ZCuipg8vbtQBvMDo49hz3ZDl6V5Fttdpl2iyA9JO2aeHaTG919gKHkwHdwmzOMq6HTdvE8ZrGB0A04avyG1z1350JwcYc8UXjxT3pGi3yOsos28MRLeh0gXtwRKS87ygqcluwErL99zh5kn6v2rMaWpZxxyzKP3LL0PXcazuS6xeuO34OQbCAuDWOWlgJxI2EQ7OKZMHloSzCPNQS1t8D33VQMuzSCY4vzAxuBWP%2F%2BEoE10C%2BZ01dSlr8xPmuSS6bnJvT4vRB6nzc4ZwA7fh%2BGIBZo7yAmIaEwjXdPNoUjf4nQhweQlT7ObDGS20D2pKoRpzWrOU2jdyIpcYl911l6TYbfn%2Bz2MacEbUOCttUb2JYA9jStW5bhDJtXqbZ53mpzne%2F%2BJGAgcMsN%2BF8C1unFOH4uyv4vUrtnS5%2FvL9JWkgUfQpIlgb%2BT%2FIYd5o%2BE55aKm67uV0L4lz8h%2FJCiR4Pa193xn%2FJp88%2BzwfXttH%2B3JrlrtyfTeLnCWbP6dWKWPlc%2F8tRv%2Fgc%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E)

**Comment by dan-homebrew** [comment]
> Ichigo
> ![image](https://github.com/user-attachments/assets/33e598a6-486b-4de0-a10a-23e6c129acf7)

@louis-jan I realize I may have been mis-communicated by asking for Ichigo to be a fork of Jan. 

I would like to clarify my position: Jan should support Ichigo as a model

## Direction
- Jan should support Ichigo as a model
- Jan (web, containerized) should be used to run https://ichigo.homebrew.ltd
- We can have a special UI route, to hide Jan's desktop UI and instead have a simple UI for Ichigo

## Scope

I would like to use Ichigo to drive improvements at Jan and Cortex: 

**Jan**
- Jan should support DB option for persistence (in addition to the FS we already have)
- Jan should be able to have Threads that are linked to Users or Sessions (i.e. enable multi-user Jan in the future)

**Comment by dan-homebrew** [comment]
Decision: Keep ichigo.homebrew.ltd demo separate

**Structure**
- Python backend (vLLM + WhisperSpeech)
- Simple UI
- No persistence (outside of saving voice snippets)
- No "feedback"
- No scaling

**Assignees**
- @nguyenhoangthuan99 backend
- @urmauur UI

**Comment by 0xSage** [comment]
## Fish vs Whisper TTS
1. "Fish is faster" Can we somewhat quantify this. Doesn't have to be super rigorous.
2. Whisper is compatible with a future version of Ichigo

**Comment by tikikun** [comment]
> @nguyenhoangthuan99 , I'm excited to see the progress you're making on the backend for the demo! I have a few questions to help me understand your design choices:
> 
> 1. When you say "Fish is faster," could you give me a rough estimate of the speedup we can expect? I'd love to understand the trade-offs with quality degradation.
> 2. I noticed that Ichigo uses Whisper semantic tokens, but Fish is incompatible with a future version of Ichigo that outputs semantic tokens directly. Can you help me understand why this isn't a concern for you?
> 3. I was a bit concerned by the demo this morning - the performance of Fish seemed a bit stilted. Are there any plans to improve this aspect, or is it not a priority?

1. We can get tangible number on this front, but the idea is to get the demo out asap.
2. This shouldn't be an issue unless we want to go full sems-to-sems model, right now it's still sems-to-text. Currently it's just replace a sound model with text input, which is trivial.
3. Chunking needs  some optimization, if you chunk the data input to WhisperSpeech it will still have similar issue. We need to make some logic around chunking size.

**Comment by nguyenhoangthuan99** [comment]
I just finished Test both whisper speech and fish-speech and here is the result

I tested with this prompt
```
In the realm of advanced technology, the evolution of artificial intelligence stands as a 
monumental achievement. This dynamic field, constantly pushing the boundaries of what 
machines can do, has seen rapid growth and innovation. From deciphering complex data 
patterns to driving cars autonomously, AI's applications are vast and diverse.
```
| _    | Whisper    | Fish speech |
| -------- | -------- | ------- |
| VRAM| 9 GB  |  2 GB   |
| Time spend| 105 s | 4 s     |

**Comment by tikikun** [comment]
https://github.com/user-attachments/assets/b4f5bf1f-4f5f-42ed-8bc4-01ac7e356ff5

**Comment by tikikun** [comment]
its done
